dataset_path: "softrules/tacred/processed/dev.jsonl"
rules_path  : "softrules/tacred/processed/train_rules"
dataset_name: "tacred"
thresholds: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99, 0.999]
gensim_model:
  fname    : "softrules/models/glove.6B.50d.txt"
  # fname    : "softrules/models/glove.6B.100d.txt"
  # fname    : "softrules/models/glove.6B.200d.txt"
  # fname    : "softrules/models/glove.840B.300d.txt"
  binary   : False
  no_header: True
  
use_full_sentence         : False
number_of_words_left_right: 0
skip_unknown_words        : True
mode_of_application       : "apply_rules_with_threshold"
print_confusion_matrix    : False